When type translation crashes, report an error including the source location.
tsickle should not throw errors during type translation. However this can
happen in case of bugs, e.g. due to stack overflows, TypeErrors, or similar
conditions.

In these situations, the error is usually caused by a specific odd type that
tsickle cannot translate. However locating the type from the crash is usually
hard: there's no information where the problem occurred.

This change catches Errors and annotates them with the current location, then
re-throws. The intention is to make debugging easier while not interfering with
error handling (i.e. not catching OutOfMemory errors or similar, which is
usually fraught with danger).

Alternative approaches not taken:
- just reporting a regular compilation error and continuing.
  this risks running into very undefined behaviour under certain error
  conditions (e.g. when running out of memory).
- exception chaining to preserve the cause - doesn't exist in JavaScript.
- throwing a new error including e.stack in the message - it seems cleaner
  to retain the original error object.

PiperOrigin-RevId: 384172922